# Generated by Django 5.0.3 on 2024-03-25 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
