# Generated by Django 5.0.3 on 2024-03-26 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estore', '0004_remove_order_date_created_order_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.FloatField(),
        ),
    ]
